[project]
name = "dylib"
version = "0.0.2"
authors = ["Simon Wollwage"]
license = "BSD-3-Clause"
description = "Standalone version of former dylib module"

[dependencies]
libc = "*"
winapi = "*"
kernel32-sys = "*"

[lib]

name = "dylib"
crate-type = ["rlib"]
